name: flut_sponsorin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  
  curved_navigation_bar: ^1.0.3
  flutter:
    sdk: flutter
  intl: ^0.19.0
  path: ^1.8.3
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.1.5

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
